<?php

declare(strict_types=1);

namespace {VENDOR}\{EXTENSION}\Xclass;

use TYPO3\CMS\Core\Context\Context;
use TYPO3\CMS\Core\Domain\Repository\PageRepository;
use TYPO3\CMS\Core\Utility\GeneralUtility;

class PageLinkBuilder extends \TYPO3\CMS\Frontend\Typolink\PageLinkBuilder
{

    /**
     * Resolves page and if a translated page was found, resolves that to its
     * language parent, adjusts `$linkDetails['pageuid']` (for hook processing)
     * and modifies `$configuration['language']` (for language URL generation).
     *
     * @param array $linkDetails
     * @param array $configuration
     * @param bool $disableGroupAccessCheck
     * @return array
     */
    protected function resolvePage(array &$linkDetails, array &$configuration, bool $disableGroupAccessCheck): array
    {
        $page = [];
        $langAspect = GeneralUtility::makeInstance(Context::class)->getAspect('language');


        // JB: I tried to check $configuration['language'], and it would work fine in "Submenu Datasets"
        // JB: $configuration['language'] was always empty (in my case) for Links, generated by the Menu processor in fluid template
        if($langAspect->get('id') !== 0) {
            //JB: Check if Overlay Page of the shortcut exists
            $pageRepository = $this->buildPageRepository($langAspect);
            $page = $pageRepository->getPage($linkDetails['pageuid'], $disableGroupAccessCheck);
        }


        if(empty($page)){
            // JB: if there is no overlay, initialize default behaviour
            $pageRepository = $this->buildPageRepository();
            // Looking up the page record to verify its existence
            // This is used when a page to a translated page is executed directly.
            $page = $pageRepository->getPage($linkDetails['pageuid'], $disableGroupAccessCheck);

        }



        if (empty($page) || !is_array($page)) {
            return [];
        }
        $page = $this->resolveShortcutPage($page, $pageRepository, $disableGroupAccessCheck);

        $languageField = $GLOBALS['TCA']['pages']['ctrl']['languageField'] ?? null;
        $languageParentField = $GLOBALS['TCA']['pages']['ctrl']['transOrigPointerField'] ?? null;
        $language = (int)($page[$languageField] ?? 0);

        // The page that should be linked is actually a default-language page, nothing to do here.
        if ($language === 0 || empty($page[$languageParentField])) {
            return $page;
        }

        // Let's fetch the default-language page now
        $languageParentPage = $pageRepository->getPage(
            $page[$languageParentField],
            $disableGroupAccessCheck
        );
        if (empty($languageParentPage)) {
            return $page;
        }
        // Check for the shortcut of the default-language page
        $languageParentPage = $this->resolveShortcutPage($languageParentPage, $pageRepository, $disableGroupAccessCheck);

        // Set the "pageuid" to the default-language page ID.
        $linkDetails['pageuid'] = (int)$languageParentPage['uid'];
        $configuration['language'] = $language;
        return $languageParentPage;
    }

    /**
     * Checks if page is a shortcut, then resolves the target page directly
     */
    protected function resolveShortcutPage(array $page, PageRepository $pageRepository, bool $disableGroupAccessCheck): array
    {
        try {
            $page = $pageRepository->resolveShortcutPage($page, false, $disableGroupAccessCheck);
        } catch (\Exception $e) {
            // Keep the existing page record if shortcut could not be resolved
        }
        return $page;
    }

}
